version: '3'
services:
  nginx:
    image: nginx:1.17.10
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ${PWD}:/usr/share/nginx/html
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 5s
      timeout: 3s
      retries: 3

  # k6:
  #   image: grafana/k6
  #   #platform: linux/amd64
  #   command: ["run", "--vus", "10", "--duration", "30s"]
  #   depends_on:
  #     - nginx
